version: '3.9'

services:
  db_service:
    image: postgres:14.2-alpine
    container_name: db_teste_container
    restart: always
    # environment:
    #   POSTGRES_USER: admin
    #   POSTGRES_PASSWORD: admin123
    #   POSTGRES_DB: db_teste
    #   PGDATA: /var/lib/postgres
    env_file:
      - .env
    ports:
      - '5432:5432'

  # tecnospeed_api_service:
  #   container_name: tecnospeed_api_container
  #   image: tecnospeed_api_image
  #   depends_on:
  #     - tecnospeed_db_service
  #   # command: bash -c ""
  #   build: ./
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   ports:
  #     - "3333:3333"
  #   links:
  #     - tecnospeed_db_service
  #   depends_on:
  #     - tecnospeed_db_service
