version: "3"

services:
  tecnospeed_db_service:
    container_name: tecnospeed_db_container
    restart: always
    image: postgres
    environment:
      POSTGRES_DB: tecnospeed_db
      POSTGRES_USER: user_tecnospeed
      POSTGRES_PASSWORD: tecnospeedpass
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  tecnospeed_api_service:
    container_name: tecnospeed_api_container
    image: tecnospeed_api_image
    depends_on:
      - tecnospeed_db_service
    # command: bash -c ""
    build: ./
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3333:3333"
    links:
      - tecnospeed_db_service
    depends_on:
      - tecnospeed_db_service
